name: product_catalog
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1
  path_provider: ^2.1.4
  uuid: ^4.4.2
  flutter_native_splash: ^2.4.1

dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

flutter_native_splash:
  image: assets/images/logo.png
  background_image: assets/images/logo.png
  android: true
  ios: true
  web: false
  android_12:
    image: assets/images/logo.png